### ISSUE TITLE
Support liquibase 4.x

### ISSUE THREAD

**Issue by CyrilDevOps** [liquibase/liquibase-percona#56]
Are you updating your extension to be able to use it with liquibase 4.x ?
I tried using it with liquibase 4.x and liquibase-compat lib, but it still
failed with : 
[2021-01-19 23:06:03] SEVERE [liquibase.integration] Unexpected error running Liquibase: 'liquibase.logging.LogFactory liquibase.logging.LogFactory.getInstance()'
java.lang.NoSuchMethodError: 'liquibase.logging.LogFactory liquibase.logging.LogFactory.getInstance()'

(it was logged by the liquibase team :
https://github.com/liquibase/liquibase/issues/1641
)

Thanks.

**Comment by adangel** [comment]
The update is in progress (see #59). Would you be able to test this extension, once it's ready? So far, the integration tests run successfully, but they all are artificial and not a "real world" usage example...

**Comment by nholmes3** [comment]
Hello @adangel, I would be happy to help test this on some of my databases once it is ready. I would love to have this as soon as possible! Thank you for all your work to support it.

**Comment by adangel** [comment]
@nholmes3 Thanks for the offer!

You can now test liquibase-percona-2.0.0-SNAPSHOT - see https://github.com/liquibase/liquibase-percona#using-snapshots

**Comment by CyrilDevOps** [comment]
Hi,
did a quick test with the snapshot  liquibase-percona-2.0.0-20210128.103441-2.jar
it seems to work ok.

Can you explain the xml namespace for the usePercona flag ?
(I have no experience on xml changeset)

**Comment by nholmes3** [comment]
> @nholmes3 Thanks for the offer!
> 
> You can now test liquibase-percona-2.0.0-SNAPSHOT - see https://github.com/liquibase/liquibase-percona#using-snapshots

I haven't seen any problems so far in my testing with snapshot liquibase-percona-2.0.0-20210128.103441-2.jar

Do you know when 2.0.0 will be officially released?

Thanks!

**Comment by adangel** [comment]
@CyrilDevOps @nholmes3 Thanks for testing!

I've just now released 2.0.0. You can download it from https://github.com/liquibase/liquibase-percona/releases/tag/liquibase-percona-2.0.0 - the upload to maven-central will take a while (maybe tomorrow).

**Comment by adangel** [comment]
> Can you explain the xml namespace for the usePercona flag ?
> (I have no experience on xml changeset)

I actually changed the namespace once more - it's in the release notes.
You just need to declare the namespcace in your xml changeset, so that you can use attributes in liquibase-extensions. Otherwise only the attributes that liquibase itself understands are supported.
It doesn't really matter, which value you use as the namespace for the extension, as long as it is different from the main liquibase. But there are some recommendations (see https://liquibase.jira.com/wiki/spaces/CONTRIB/pages/2424883/Contributing).

So I settled for `http://www.liquibase.org/xml/ns/dbchangelog-ext/liquibase-percona`. Having a namespace also allows to define a xsd schema, so that the changeset xml can be validated.
